FROM public.ecr.aws/lambda/python:3.9


# Copy function code and other necessary files
COPY gpt_lambda.py ${LAMBDA_TASK_ROOT}
COPY roberta_lambda.py ${LAMBDA_TASK_ROOT}
COPY roberta_model.py ${LAMBDA_TASK_ROOT}
COPY stanza_model.py ${LAMBDA_TASK_ROOT}
# Set environment variable for Lambda execution
ENV IS_LAMBDA=true



# Install Python dependencies
#RUN pip install torch transformers pandas boto3 -t /opt/python
RUN pip install python-dotenv
RUN pip install numpy==1.24.4 pandas boto3 scikit-learn
RUN pip install torch==2.0.0+cpu torchvision==0.15.0+cpu torchaudio==2.0.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
RUN pip install  transformers
RUN pip install openai==0.28
# Copy function code
COPY lambda_function.py ${LAMBDA_TASK_ROOT}

# Command to run
CMD ["gpt_lambda.lambda_handler"]