# -*- coding: utf-8 -*-
"""Stanza_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12hH_liruz5qYsQgJDfVH3vDAXdTlasfx
"""

import stanza
import pandas as pd
from sklearn.metrics import classification_report

# Load Stanza NLP Model
stanza.download("en")
nlp = stanza.Pipeline(lang="en", processors="tokenize,sentiment")

def get_stanza_sentiment(text, nlp):
    doc = nlp(text)
    sentiment_score = doc.sentences[0].sentiment  # (0 = Negative,1 = Positive)
    return "Positive" if sentiment_score == 2 else "Negative"

# Load Data
df = pd.read_csv(r"C:\Users\291688\Downloads\Sentiment_Analysis_NLP_Model\channel_partner_feedback.csv")  # Ensure it has 'text' and 'true_label' columns

# Analyze Sentiment for Stanza
df["stanza_prediction"] = df["Feedback_Text"].apply(lambda x: get_stanza_sentiment(x, nlp))

# Print classification report
print("\n Stanza Model Performance:")
print(classification_report(df["Sentiment"], df["stanza_prediction"]))

df















